backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "블로그"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "카테고리", name: "category", widget: "select", options: ["마진거래", "매매기법", "경제·금융"]}
      - {label: "요약", name: "summary", widget: "string"}
      - {label: "본문", name: "body", widget: "markdown"}
